/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/Layouts/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/Layouts/AppSidebar.vue')['default']
    AttendanceChart: typeof import('./src/components/charts/AttendanceChart.vue')['default']
    AttendanceRequestModal: typeof import('./src/components/AttendanceRequestModal.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    Birthday: typeof import('./src/components/Birthday.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    CheckTime: typeof import('./src/components/CheckTime.vue')['default']
    ChildTable: typeof import('./src/components/ChildTable.vue')['default']
    Clock: typeof import('./src/components/Clock.vue')['default']
    CountChart: typeof import('./src/components/charts/CountChart.vue')['default']
    DepartmentNode: typeof import('./src/components/DepartmentNode.vue')['default']
    DepartmentStructureBlock: typeof import('./src/components/DepartmentStructureBlock.vue')['default']
    DesktopLayout: typeof import('./src/components/Layouts/DesktopLayout.vue')['default']
    Fields: typeof import('./src/components/Fields.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    HomeIcon: typeof import('./src/components/Icons/HomeIcon.vue')['default']
    Listview: typeof import('./src/components/Listview.vue')['default']
    NewsList: typeof import('./src/components/NewsList.vue')['default']
    Notifications: typeof import('./src/components/Notifications.vue')['default']
    OneDayChart: typeof import('./src/components/charts/OneDayChart.vue')['default']
    PageGrid: typeof import('./src/components/PageGrid.vue')['default']
    QuickLink: typeof import('./src/components/QuickLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./src/components/Section.vue')['default']
    SidebarLink: typeof import('./src/components/SidebarLink.vue')['default']
    TextEditor: typeof import('./src/components/TextEditor.vue')['default']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
  }
}
