/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/Layouts/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/Layouts/AppSidebar.vue')['default']
    DesktopLayout: typeof import('./src/components/Layouts/DesktopLayout.vue')['default']
    Fields: typeof import('./src/components/Fields.vue')['default']
    Listview: typeof import('./src/components/Listview.vue')['default']
    Notifications: typeof import('./src/components/Notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./src/components/Section.vue')['default']
    SidebarLink: typeof import('./src/components/SidebarLink.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    TourPDF: typeof import('./src/components/tourPDF.vue')['default']
    UserDropdown: typeof import('./src/components/UserDropdown.vue')['default']
  }
}
